version: '3.4'

services:
  instagramscrapeexpress:
    image: instagramscrapeexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      COIN_HOST: host.docker.internal
    ports:
      - 8088:8088
    # network_mode: host